server:
  port: 8081
  servlet:
    context-path: /api/v1/roomBillz
    
spring:
  application:
    name: ROOMBILLZ-SERVICE

#Database Configuration       
  datasource:
    url: jdbc:mysql://localhost:3306/roombillz
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
 
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  cloud:
    compatibility-verifier:
      enabled: false

#Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"

#Custom mapping to use in annotations/values
kafka:
  topics:
    roomBillz: roomBillz-topic
    notification: roomBillz-notification-topic
  groups:
    roomBillz: roombillz-group
    notification: roomBillz-notification-group

#File download path      
invoice:
    upload:
      path: "D:\\RoomBillz_Document\\Invoice\\"
      
download:
    excelReport:    
      path: "D:\\RoomBillz_Document\\ExcelReport\\"
    excelGroupReport:    
      path: "D:\\RoomBillz_Document\\ExcelGroupReport\\"
      
#Acatuator Configuration    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

