server:
  port: 8081
  servlet:
    context-path: /api/v1/roomBillz
    
spring:
  application:
    name: ROOMBILLZ-SERVICE
       
  datasource:
    url: jdbc:mysql://localhost:3306/roombillz
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
 
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
      
invoice:
    upload:
      path: "D:\\RoomBillz_Document\\Invoice\\"
      
download:
    excelReport:    
      path: "D:\\RoomBillz_Document\\ExcelReport\\"
    excelGroupReport:    
      path: "D:\\RoomBillz_Document\\ExcelGroupReport\\"
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

